version: '3'
services:
  socks5-build:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GOLANG_VERSION: 1.19.1
    container_name: socks5-build
    ports:
      - "1080:1080"
    dns:
      - 80.67.169.12
      - 2001:910:800::12
