version: '3'
services:
  socks5:
    image: edgd1er/go-socks5-proxy
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GOLANG_VERSION: "1.14"
    restart: unless-stopped
#    healthcheck:
#      test: ["CMD", "nc", "-v", "127.0.0.1:1080"]
    environment:
      #Set proxy user (also required existed PROXY_PASS)
      "PROXY_USER": ""
      #Set proxy password for auth, used with PROXY_USER
      "PROXY_PASSWORD": ""
      #Set listen port for application inside docker container
      "PROXY_PORT": 1080
    ports:
      - "1080:1080"
    dns:
      - 80.67.169.12
      - 2001:910:800::12
